repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args:
          [
            --recursive,
            --in-place,
            --expand-star-imports,
            --remove-all-unused-imports,
            --ignore-init-module-imports,
            --remove-duplicate-keys,
            --remove-unused-variables,
          ]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--exclude=__init__.py, --max-line-length=88]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]
