version: "3"

services:
  db:
    image: neo4j:5.8.0
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc"]
