[tool.poetry]
name = "catalog-api"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8.1"
flaat = "^1.1.8"
fastapi = "^0.95.2"
uvicorn = "^0.22.0"
neomodel = "^5.0.1"
pydantic = {extras = ["email"], version = "^1.10.9"}

[tool.poetry.dev-dependencies]
black = "^23.3.0"
flake8 = "^6.0.0"
pytest = "^7.3.1"
pytest-cov = "^4.1.0"
nox = "^2023.4.22"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
