cmdb:
  base_url: http://localhost:8000/
  api_ver:
    flavors: v1
    identity_providers: v1
    images: v1
    locations: v1
    projects: v1
    providers: v1
    quotas: v1
    services: v1
    slas: v1
    user_groups: v1

oidc_agent_accounts:
  - https://iam.cloud.infn.it/

openstack:
  - name: recas-ba
    status: active
    auth_url: https://keystone.recas.ba.infn.it:443
    identity_providers:
      - name: infn-cloud
        protocol: openid
        endpoint: https://iam.cloud.infn.it/
        group_claim: groups
    slas:
      - doc_uuid: edfda059a23c439f8ffc06edd484e1a0
        start_date: 2023-09-10
        end_date: 2023-09-25
        project:
          name: infn-cloud-ops
          domain: default
          group:
            name: test
            idp: https://iam.cloud.infn.it/
          per_user_limits:
            compute:
              cores: 2
              ram: 2
              public_ips: 2
            block_storage:
              gigabytes: 2
      - doc_uuid: bdfda059a23c439f8ffc06edd484e1a0
        start_date: 2023-09-11
        end_date: 2024-09-25
        project:
          id: edfda059a23c439f8ffc06edd484efa0
          group:
            name: prova
            idp: https://iam.cloud.infn.it/
      - doc_uuid: cdfda059a23c439f8ffc06edd484e1a0
        start_date: 2023-09-11
        end_date: 2023-10-25
        project:
          id: 83be7870dbb54d4a988f89ea77e9e2b9
          group:
            name: pippo
            idp: https://iam.cloud.infn.it/
    is_public: false
    support_emails:
      - giovanni.savarese@ba.infn.it
    location:
      site: Bari
      country: Italy

  - name: cloud-cnaf
    status: active
    auth_url: https://cloud-api-pub.cr.cnaf.infn.it:5000/v3
    identity_providers:
      - endpoint: https://iam.cloud.infn.it/
        name: infn-cc
        protocol: openid
        group_claim: groups
    slas:
      - doc_uuid: c2bb880f0aa443a49abcbbbe2e96b48b
        start_date: 2023-10-11
        end_date: 2023-10-25
        project:
          id: 12bb88070aa443a494bcbbbe2e96b48b
          group:
            name: test
            idp: https://iam.cloud.infn.it/
    is_public: false
    support_emails:
      - giovanni.savarese@ba.infn.it
    location:
      site: Bologna
      country: Italy
