cmdb:
  url: http://localhost:8000/
  api_ver_flavors: "v1"
  api_ver_identity_providers: "v1"
  api_ver_images: "v1"
  api_ver_locations: "v1"
  api_ver_projects: "v1"
  api_ver_providers: "v1"
  api_ver_quotas: "v1"
  api_ver_services: "v1"
  api_ver_slas: "v1"
  api_ver_user_groups: "v1"

oidc_agent_accounts:
  - https://iam.cloud.infn.it/

openstack:
  - name: recas-ba
    auth_url: https://keystone.recas.ba.infn.it:443
    identity_providers:
      - name: infn-cloud
        protocol: openid
        endpoint: https://iam.cloud.infn.it/
        group_claim: groups
    projects:
      - name: infn-cloud-ops
        domain: default
      - id: edfda059a23c439f8ffc06edd484efa0
      - id: 83be7870dbb54d4a988f89ea77e9e2b9
    is_public: false
    support_emails:
      - "giovanni.savarese@ba.infn.it"
    location:
      name: "ReCas-BA"
      country: "Italy"
