name: Linting

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      # Lint using Ruff
      - name: Use Ruff linter and formatter
        uses: chartboost/ruff-action@v1
        with:
          src: "backend"
